services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: lovekut3A
      MYSQL_DATABASE: shopping
    volumes:
      - shopping-data:/var/lib/mysql
    ports:
      - 3307:3306
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - HOST=host.docker.internal
    ports:
      - 3002:3002    
volumes:
  shopping-data:
